name: Build & Upload Debug/Release APKs to Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build Debug and Release APKs
      run: |
        cd android/vision-quickstart
        ./gradlew assembleDebug
        ./gradlew assembleRelease

    - name: Upload APK to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          android/vision-quickstart/app/build/outputs/apk/debug/vision-quickstart-debug.apk
          android/vision-quickstart/app/build/outputs/apk/release/vision-quickstart-release-unsigned.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
